Executable bit
Signed-off-by: GitHub <noreply@github.com>

diff --git a/root/etc/s6-overlay/s6-rc.d/init-kimai-config/run b/root/etc/s6-overlay/s6-rc.d/init-kimai-config/run
--- a/root/etc/s6-overlay/s6-rc.d/init-kimai-config/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-kimai-config/run
@@ -1,20 +1,60 @@
 #!/usr/bin/with-contenv bash
 # shellcheck shell=bash
 
-# make our folders
-mkdir -p \
-    /config/{cache,data,log,packages,plugins,sessions}
+DB_VALID=$(php -r 'echo filter_var(getenv("DATABASE_URL"), FILTER_VALIDATE_URL, FILTER_FLAG_PATH_REQUIRED);')
 
-symlink -l /app/www/var /config
-
-if [[ -n "${DATABASE_URL}" ]]; then
-    cd /app/www || exit 1
-    s6-setuidgid abc bin/console kimai:install -n
-    s6-setuidgid abc bin/console kimai:update -n
-else
-    echo "DATABASE_URL not set"
+if [[ ${DATABASE_URL+x} == "" ]] || [[ ${DB_VALID+x} == "NULL" ]]; then
+    cat <<-EOF
+    ********************************************************
+    ********************************************************
+    *                                                      *
+    *                         !!!!                         *
+    *     DATABASE_URL environment variable is not set     *
+    *                          OR                          *
+    *    DATABASE_URL environment variable is not valid    *
+    *                                                      *
+    *              Please refer to the README              *
+    *                                                      *
+    *                                                      *
+    ********************************************************
+    ********************************************************
+EOF
     sleep infinity
 fi
 
+# make our folders
+mkdir -p \
+    /config/www/var/{cache,data,log,packages,plugins,sessions}
+
+rm -rf /app/www/var
+symlink -l /app/www/var /config/www/var
+
+DB_HOST=$(php -r 'echo parse_url(getenv("DATABASE_URL"), PHP_URL_HOST);')
+DB_PORT=$(php -r 'echo parse_url(getenv("DATABASE_URL"), PHP_URL_PORT) ?? 3306;')
+
+# check for the mysql endpoint
+echo "Waiting for DB to be available"
+END=$((SECONDS + 30))
+while [[ ${SECONDS} -lt ${END} ]]; do
+    if [[ $(/usr/bin/nc -w1 "${DB_HOST}" "${DB_PORT}" | tr -d '\0') ]]; then
+        if [[ -n "${RUN}" ]]; then
+            break
+        fi
+        RUN="RAN"
+        # we sleep here again due to first run init on DB containers
+        if [[ ! -f /dbwait.lock ]]; then
+            sleep 5
+        fi
+    else
+        sleep 1
+    fi
+done
+# set lockfile to avoid DB waits for this specific container
+touch /dbwait.lock
+
+cd /app/www || exit 1
+s6-setuidgid abc bin/console kimai:install -n
+s6-setuidgid abc bin/console kimai:update -n
+
 lsiown -R abc:abc \
-    /config
+    /config/www
